services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: devsrch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Brooklyn11
    volumes:
      - postgres_data:/var/lib/postgresql/data


  web:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      - DB_NAME=devsrch
      - DB_USER=postgres
      - DB_PASSWORD=Brooklyn11
      - DB_HOST=devsrch
      - DB_PORT=5432
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    context: .

volumes:
  postgres_data: {}
