version: "3.8"  # Лучше явно указать версию

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: devsrch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Brooklyn11
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: ./app
    restart: always
    depends_on:
      - db
    environment:
      - DB_NAME=devsrch
      - DB_USER=postgres
      - DB_PASSWORD=Brooklyn11
      - DB_HOST=db  # Исправили хост
      - DB_PORT=5432
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app  # Исправленный путь

volumes:
  postgres_data: {}
